import{BadRequestException,ConflictException,Injectable,NotFoundException,ServiceUnavailableException}from'@nestjs/common';import{database,Prisma}from'@uaprep/db';import type{RequestContext}from'../request-context.js';
export interface VerifiedPayment{provider:string;providerTxnId:string;orderId:string;amount:number;currency:string;successful:boolean;payload:Prisma.InputJsonValue}
export abstract class PaymentGatewayVerifier{abstract verify(payload:unknown):Promise<VerifiedPayment>;}
@Injectable()export class UnconfiguredGatewayVerifier extends PaymentGatewayVerifier{async verify():Promise<VerifiedPayment>{throw new ServiceUnavailableException('Payment gateway verification is not configured');}}
@Injectable()export class CommerceService{constructor(private readonly verifier:PaymentGatewayVerifier){}
async catalog(ctx:RequestContext){return database.product.findMany({where:{tenantId:ctx.principal.tenantId,active:true},include:{prices:{where:{active:true}}}});}
async createOrder(ctx:RequestContext,priceId:string){const price=await database.price.findFirst({where:{id:priceId,active:true,product:{tenantId:ctx.principal.tenantId,active:true}},include:{product:true}});if(!price)throw new NotFoundException();return database.order.create({data:{tenantId:ctx.principal.tenantId,userId:ctx.principal.userId,productId:price.productId,priceId:price.id,amount:price.amount,currency:price.currency}});}
async webhook(payload:unknown){const verified=await this.verifier.verify(payload);if(!verified.successful)throw new BadRequestException('Gateway did not verify a successful transaction');const order=await database.order.findUnique({where:{id:verified.orderId}});if(!order)throw new NotFoundException();if(Number(order.amount)!==verified.amount||order.currency!==verified.currency)throw new BadRequestException('Payment amount or currency mismatch');return database.$transaction(async tx=>{const prior=await tx.payment.findUnique({where:{provider_providerTxnId:{provider:verified.provider,providerTxnId:verified.providerTxnId}}});if(prior){if(prior.orderId!==order.id)throw new ConflictException('Transaction replayed for another order');return prior;}const payment=await tx.payment.create({data:{orderId:order.id,provider:verified.provider,providerTxnId:verified.providerTxnId,amount:verified.amount,currency:verified.currency,status:'VALIDATED',validatedAt:new Date(),providerPayload:verified.payload}});await tx.order.update({where:{id:order.id},data:{status:'PAID'}});await tx.entitlement.upsert({where:{userId_productId_orderId:{userId:order.userId,productId:order.productId,orderId:order.id}},create:{userId:order.userId,productId:order.productId,orderId:order.id},update:{revokedAt:null}});return payment;});}
async entitlements(ctx:RequestContext){return database.entitlement.findMany({where:{userId:ctx.principal.userId,revokedAt:null,OR:[{endsAt:null},{endsAt:{gt:new Date()}}]},include:{product:true}});}}
