export const FUTURE_FEATURE_FLAGS = ['PREPARE','PRACTICE','READINESS','STUDY_PLAN','ADMISSION_TRACKER','AI_TUTOR','AI_QUESTION_DRAFTING','B2B_TENANTS'] as const;
export type FutureFeatureFlag = (typeof FUTURE_FEATURE_FLAGS)[number];
