import{randomInt}from'node:crypto';
import{BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';
import{database,Prisma}from'@uaprep/db';
import{isDeadlineExpired,scoreObjectiveAttempt,type ObjectiveScoringRule}from'@uaprep/core';
import type{RequestContext}from'../request-context.js';
import{saveAnswerSchema,scoringPolicySchema,startAttemptSchema,targetSchema}from'./dto.js';
const shuffle=<T>(values:readonly T[])=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=randomInt(i+1);[copy[i],copy[j]]=[copy[j]!,copy[i]!];}return copy;};

@Injectable()
export class ExamsService{
  async createScoringPolicy(ctx:RequestContext,input:unknown){const data=scoringPolicySchema.parse(input);const latest=await database.scoringPolicyVersion.aggregate({where:{tenantId:ctx.principal.tenantId,policyKey:data.policyKey},_max:{version:true}});return database.scoringPolicyVersion.create({data:{tenantId:ctx.principal.tenantId,policyKey:data.policyKey,version:(latest._max.version??0)+1,rules:data.rules as Prisma.InputJsonObject,publishedAt:new Date()}});}
  async setTarget(ctx:RequestContext,input:unknown){const data=targetSchema.parse(input);const university=await database.university.findFirst({where:{id:data.universityId,tenantId:ctx.principal.tenantId}});if(!university)throw new BadRequestException('University does not belong to tenant');if(data.programId&&!await database.program.findFirst({where:{id:data.programId,universityId:data.universityId}}))throw new BadRequestException('Program does not belong to university');return database.studentTarget.create({data:{tenantId:ctx.principal.tenantId,studentId:ctx.principal.userId,universityId:data.universityId,programId:data.programId??null,intake:data.intake??null,examDate:data.examDate??null}});}
  async library(ctx:RequestContext){return database.mockVersion.findMany({where:{status:'PUBLISHED',mock:{tenantId:ctx.principal.tenantId}},select:{id:true,version:true,publishedAt:true,mock:{select:{id:true,name:true}},sections:{select:{name:true,position:true,durationSeconds:true,totalMarks:true,_count:{select:{items:true}}}}},orderBy:{publishedAt:'desc'}});}
  async start(ctx:RequestContext,input:unknown){
    const data=startAttemptSchema.parse(input);
    const existing=await database.attempt.findUnique({where:{studentId_startKey:{studentId:ctx.principal.userId,startKey:data.startKey}}});
    if(existing)return this.examPayload(ctx,existing.id);
    const mock=await database.mockVersion.findFirst({
      where:{id:data.mockVersionId,status:'PUBLISHED',mock:{tenantId:ctx.principal.tenantId}},
      include:{sections:{orderBy:{position:'asc'},include:{items:{orderBy:{position:'asc'},include:{questionVersion:{include:{options:true}}}}}}},
    });
    if(!mock)throw new NotFoundException();
    const questionOrder=mock.sections.map(section=>({sectionId:section.id,questionVersionIds:shuffle(section.items.map(item=>item.questionVersionId))}));
    const optionOrder=Object.fromEntries(mock.sections.flatMap(section=>section.items.map(item=>[item.questionVersionId,shuffle(item.questionVersion.options.map(option=>option.position))])));
    const startedAt=new Date();const duration=mock.sections.reduce((sum,section)=>sum+section.durationSeconds,0);const deadlineAt=new Date(startedAt.getTime()+duration*1000);
    const policy=await database.scoringPolicyVersion.findUnique({where:{id:mock.scoringPolicyVersionId}});if(!policy?.publishedAt)throw new ConflictException('Published scoring policy is missing');
    let attempt;
    try{attempt=await database.$transaction(async tx=>{const created=await tx.attempt.create({data:{tenantId:ctx.principal.tenantId,studentId:ctx.principal.userId,mockVersionId:mock.id,scoringPolicyVersionId:mock.scoringPolicyVersionId,startKey:data.startKey,status:'IN_PROGRESS',startedAt,deadlineAt}});await tx.attemptSnapshot.create({data:{attemptId:created.id,patternVersionId:mock.patternVersionId,scoringPolicyVersionId:mock.scoringPolicyVersionId,questionOrder,optionOrder,reviewPolicy:(policy.rules as {reviewPolicy?:Prisma.InputJsonValue}).reviewPolicy??{}}});await tx.attemptEvent.create({data:{attemptId:created.id,eventType:'ATTEMPT_STARTED'}});return created;});}
    catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const raced=await database.attempt.findUniqueOrThrow({where:{studentId_startKey:{studentId:ctx.principal.userId,startKey:data.startKey}}});return this.examPayload(ctx,raced.id);}throw error;}
    return this.examPayload(ctx,attempt.id);
  }
  async save(ctx:RequestContext,attemptId:string,input:unknown){const data=saveAnswerSchema.parse(input);const attempt=await this.ownedAttempt(ctx,attemptId);if(attempt.status!=='IN_PROGRESS')throw new ConflictException('Attempt is not accepting answers');if(!attempt.deadlineAt||isDeadlineExpired(attempt.deadlineAt,new Date()))throw new ConflictException('Attempt deadline has expired');const snapshot=attempt.snapshot?.questionOrder as {sectionId:string;questionVersionIds:string[]}[]|undefined;if(!snapshot?.some(section=>section.questionVersionIds.includes(data.questionVersionId)))throw new BadRequestException('Question is not in attempt snapshot');const existing=await database.attemptAnswer.findUnique({where:{attemptId_operationId:{attemptId,operationId:data.operationId}}});if(existing)return{revision:existing.revision,savedAt:existing.savedAt,idempotent:true};const latest=await database.attemptAnswer.aggregate({where:{attemptId,questionVersionId:data.questionVersionId},_max:{revision:true}});if(data.revision!==(latest._max.revision??0)+1)throw new ConflictException({message:'Answer revision conflict',serverRevision:latest._max.revision??0});const answer=await database.attemptAnswer.create({data:{attemptId,questionVersionId:data.questionVersionId,operationId:data.operationId,revision:data.revision,response:{selectedOptionPositions:data.selectedOptionPositions}}});return{revision:answer.revision,savedAt:answer.savedAt,idempotent:false};}
  async submit(ctx:RequestContext,attemptId:string){const attempt=await this.ownedAttempt(ctx,attemptId,true);if(attempt.score)return attempt.score;if(!['IN_PROGRESS','SUBMISSION_PENDING'].includes(attempt.status))throw new ConflictException('Attempt cannot be submitted');const latestAnswers=new Map<string,{selectedOptionPositions:number[]}>();for(const answer of [...attempt.answers].sort((a,b)=>a.revision-b.revision))latestAnswers.set(answer.questionVersionId,answer.response as {selectedOptionPositions:number[]});const items=attempt.mockVersion.sections.flatMap(section=>section.items.map(item=>({section,item})));const rules=attempt.scoringPolicy.rules as unknown as ObjectiveScoringRule;const result=scoreObjectiveAttempt(rules,items.map(({section,item})=>({questionVersionId:item.questionVersionId,sectionId:section.id,questionMarks:Number(item.questionVersion.marks),questionPenalty:Number(item.questionVersion.wrongPenalty),correctOptionPositions:item.questionVersion.options.filter(option=>option.isCorrect).map(option=>option.position),selectedOptionPositions:latestAnswers.get(item.questionVersionId)?.selectedOptionPositions??[]})));return database.$transaction(async tx=>{const locked=await tx.attempt.updateMany({where:{id:attemptId,status:{in:['IN_PROGRESS','SUBMISSION_PENDING']}},data:{status:'SUBMITTED',submittedAt:new Date()}});if(locked.count!==1){const score=await tx.attemptScore.findUnique({where:{attemptId}});if(score)return score;throw new ConflictException('Submission is already in progress');}const score=await tx.attemptScore.create({data:{attemptId,total:result.total,details:result as unknown as Prisma.InputJsonValue,sectionScores:{create:Object.entries(result.sections).map(([sectionId,total])=>({sectionId,total,details:{}}))}}});await tx.attempt.update({where:{id:attemptId},data:{status:'SCORED'}});await tx.attemptEvent.create({data:{attemptId,eventType:'ATTEMPT_SCORED',payload:{total:result.total}}});return score;});}
  async examPayload(ctx:RequestContext,id:string){const attempt=await this.ownedAttempt(ctx,id,true);const order=attempt.snapshot!.questionOrder as {sectionId:string;questionVersionIds:string[]}[];const optionOrder=attempt.snapshot!.optionOrder as Record<string,number[]>;return{id:attempt.id,status:attempt.status,startedAt:attempt.startedAt,deadlineAt:attempt.deadlineAt,serverNow:new Date(),sections:order.map(snapshotSection=>{const section=attempt.mockVersion.sections.find(item=>item.id===snapshotSection.sectionId)!;return{id:section.id,name:section.name,position:section.position,questions:snapshotSection.questionVersionIds.map(questionVersionId=>{const item=section.items.find(candidate=>candidate.questionVersionId===questionVersionId)!;const version=item.questionVersion;const positions=optionOrder[questionVersionId]??version.options.map(option=>option.position);return{id:version.id,type:version.questionType,stem:version.stem,marks:Number(version.marks),options:positions.map(position=>{const option=version.options.find(candidate=>candidate.position===position)!;return{position:option.position,content:option.content};})};})};}),answers:attempt.answers.map(answer=>({questionVersionId:answer.questionVersionId,revision:answer.revision,response:answer.response,savedAt:answer.savedAt}))};}
  private async ownedAttempt(ctx:RequestContext,id:string,_full=false){const row=await database.attempt.findFirst({where:{id,tenantId:ctx.principal.tenantId,studentId:ctx.principal.userId},include:{snapshot:true,answers:true,score:true,mockVersion:{include:{sections:{include:{items:{include:{questionVersion:{include:{options:true}}}}}}}},scoringPolicy:true}});if(!row)throw new ForbiddenException();return row;}
}
