import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { database } from '@uaprep/db';
import { assertPatternTransition, findOverlappingPatternIds, validatePatternPublication, type PatternStatus } from '@uaprep/core';
import type { RequestContext } from '../request-context.js';
import { createEvidenceSchema, createObjectiveSchema, createPatternSchema, createPatternVersionSchema, createProgramSchema, createSubjectSchema, createSubtopicSchema, createTopicSchema, createUniversitySchema, transitionPatternSchema } from './dto.js';

@Injectable()
export class AcademicService {
  async listUniversities(context:RequestContext) { return database.university.findMany({where:{tenantId:context.principal.tenantId},include:{programs:true},orderBy:{name:'asc'}}); }
  async createUniversity(context:RequestContext,input:unknown) {
    const data=createUniversitySchema.parse(input);
    return database.$transaction(async tx => { const row=await tx.university.create({data:{...data,tenantId:context.principal.tenantId}}); await tx.auditEvent.create({data:{tenantId:context.principal.tenantId,actorId:context.principal.userId,eventType:'UNIVERSITY_CREATED',resourceType:'University',resourceId:row.id,correlationId:context.correlationId,summary:{name:row.name,isDemo:row.isDemo}}}); return row; });
  }
  async createProgram(context:RequestContext,universityId:string,input:unknown) {
    const data=createProgramSchema.parse(input); await this.requireUniversity(context,universityId);
    return database.$transaction(async tx => { const row=await tx.program.create({data:{name:data.name,code:data.code??null,universityId}}); await tx.auditEvent.create({data:{tenantId:context.principal.tenantId,actorId:context.principal.userId,eventType:'PROGRAM_CREATED',resourceType:'Program',resourceId:row.id,correlationId:context.correlationId}}); return row; });
  }
  async createEvidence(context:RequestContext,universityId:string,input:unknown) {
    const data=createEvidenceSchema.parse(input); await this.requireUniversity(context,universityId);
    if (data.claims.some(c=>c.effectiveUntil&&c.effectiveFrom&&c.effectiveUntil<=c.effectiveFrom)) throw new BadRequestException('Invalid claim effective range');
    const programIds=data.claims.flatMap(c=>c.programId?[c.programId]:[]); if(programIds.length){const count=await database.program.count({where:{id:{in:programIds},universityId}});if(count!==new Set(programIds).size)throw new BadRequestException('Claim program does not belong to university');}
    return database.$transaction(async tx => { const row=await tx.evidenceSource.create({data:{universityId,claimType:data.claimType,tier:data.tier,sourceType:data.sourceType,sourceReference:data.sourceReference,snapshotHash:data.snapshotHash??null,observedAt:data.observedAt,effectiveAt:data.effectiveAt??null,nextReviewAt:data.nextReviewAt??null,notes:data.notes??null,researcherId:context.principal.userId,claims:{create:data.claims.map(claim=>({claimType:claim.claimType,statement:claim.statement,programId:claim.programId??null,intake:claim.intake??null,effectiveFrom:claim.effectiveFrom??null,effectiveUntil:claim.effectiveUntil??null}))}}}); await tx.auditEvent.create({data:{tenantId:context.principal.tenantId,actorId:context.principal.userId,eventType:'EVIDENCE_CREATED',resourceType:'EvidenceSource',resourceId:row.id,correlationId:context.correlationId,summary:{tier:row.tier,status:row.status}}}); return row; });
  }
  async approveEvidence(context:RequestContext,id:string) {
    const evidence=await database.evidenceSource.findFirst({where:{id,university:{tenantId:context.principal.tenantId}}}); if(!evidence)throw new NotFoundException(); if(evidence.tier==='D_RESEARCH_LEAD')throw new BadRequestException('Tier D evidence cannot become production-authoritative');
    return database.$transaction(async tx=>{const row=await tx.evidenceSource.update({where:{id},data:{status:'APPROVED',confidence:'VERIFIED',verifierId:context.principal.userId,claims:{updateMany:{where:{status:'DRAFT'},data:{status:'APPROVED',approvedById:context.principal.userId,approvedAt:new Date()}}}}});await tx.auditEvent.create({data:{tenantId:context.principal.tenantId,actorId:context.principal.userId,eventType:'EVIDENCE_APPROVED',resourceType:'EvidenceSource',resourceId:id,correlationId:context.correlationId}});return row;});
  }
  async createSubject(context:RequestContext,input:unknown){const data=createSubjectSchema.parse(input);return database.subject.create({data:{name:data.name,slug:data.slug,description:data.description??null,tenantId:context.principal.tenantId}});}
  async createTopic(context:RequestContext,subjectId:string,input:unknown){const data=createTopicSchema.parse(input);const subject=await database.subject.findFirst({where:{id:subjectId,tenantId:context.principal.tenantId}});if(!subject)throw new NotFoundException();return database.topic.create({data:{...data,subjectId}});}
  async createSubtopic(context:RequestContext,topicId:string,input:unknown){const data=createSubtopicSchema.parse(input);const topic=await database.topic.findFirst({where:{id:topicId,subject:{tenantId:context.principal.tenantId}}});if(!topic)throw new NotFoundException();return database.subtopic.create({data:{name:data.name,slug:data.slug,description:data.description??null,topicId}});}
  async createObjective(context:RequestContext,topicId:string,input:unknown){const data=createObjectiveSchema.parse(input);const topic=await database.topic.findFirst({where:{id:topicId,subject:{tenantId:context.principal.tenantId}},include:{subtopics:true}});if(!topic)throw new NotFoundException();if(data.subtopicId&&!topic.subtopics.some(s=>s.id===data.subtopicId))throw new BadRequestException('Subtopic does not belong to topic');return database.learningObjective.create({data:{statement:data.statement,code:data.code??null,subtopicId:data.subtopicId??null,topicId}});}
  async createPattern(context:RequestContext,universityId:string,input:unknown){const data=createPatternSchema.parse(input);await this.requireUniversity(context,universityId);return database.admissionPattern.create({data:{universityId,name:data.name}});}
  async createPatternVersion(context:RequestContext,patternId:string,input:unknown){const data=createPatternVersionSchema.parse(input);const pattern=await database.admissionPattern.findFirst({where:{id:patternId,university:{tenantId:context.principal.tenantId}}});if(!pattern)throw new NotFoundException();const uniqueEvidence=[...new Set(data.evidenceSourceIds)];const uniquePrograms=[...new Set(data.programIds)];const subjectIds=[...new Set(data.sections.flatMap(section=>section.subjectId?[section.subjectId]:[]))];const [evidenceCount,programCount,subjectCount]=await Promise.all([database.evidenceSource.count({where:{id:{in:uniqueEvidence},universityId:pattern.universityId}}),database.program.count({where:{id:{in:uniquePrograms},universityId:pattern.universityId}}),database.subject.count({where:{id:{in:subjectIds},tenantId:context.principal.tenantId}})]);if(evidenceCount!==uniqueEvidence.length)throw new BadRequestException('Evidence does not belong to pattern university');if(programCount!==uniquePrograms.length)throw new BadRequestException('Program does not belong to pattern university');if(subjectCount!==subjectIds.length)throw new BadRequestException('Subject does not belong to tenant');const last=await database.admissionPatternVersion.aggregate({where:{patternId},_max:{version:true}});return database.admissionPatternVersion.create({data:{patternId,version:(last._max.version??0)+1,intake:data.intake??null,effectiveFrom:data.effectiveFrom??null,effectiveUntil:data.effectiveUntil??null,evidenceLinks:{create:uniqueEvidence.map(evidenceSourceId=>({evidenceSourceId}))},programApplicability:{create:uniquePrograms.map(programId=>({programId}))},sections:{create:data.sections.map(section=>({name:section.name,position:section.position,subjectId:section.subjectId??null,questionType:section.questionType,questionCount:section.questionCount,marks:section.marks,durationSeconds:section.durationSeconds,wrongPenalty:section.wrongPenalty,calculatorPolicy:section.calculatorPolicy??null,...(section.passRule?{passRule:section.passRule}:{}),}))}}});}
  async transitionPattern(context:RequestContext,id:string,input:unknown){const command=transitionPatternSchema.parse(input);const row=await database.admissionPatternVersion.findFirst({where:{id,pattern:{university:{tenantId:context.principal.tenantId}}},include:{evidenceLinks:{include:{evidenceSource:true}},programApplicability:true,sections:true,pattern:true}});if(!row)throw new NotFoundException();assertPatternTransition(row.status as PatternStatus,command.to,row.evidenceLinks.filter(x=>x.evidenceSource.status==='APPROVED').length);
    if(command.to==='PUBLISHED'){if(!row.effectiveFrom)throw new BadRequestException('Effective-from is required');const issues=validatePatternPublication({evidence:row.evidenceLinks.map(x=>({...({id:x.evidenceSource.id,tier:x.evidenceSource.tier,status:x.evidenceSource.status}),...(x.evidenceSource.nextReviewAt?{nextReviewAt:x.evidenceSource.nextReviewAt}:{})})),programIds:row.programApplicability.map(x=>x.programId),effectiveFrom:row.effectiveFrom,...(row.effectiveUntil?{effectiveUntil:row.effectiveUntil}:{}),sections:row.sections.map(x=>({...x,marks:Number(x.marks),wrongPenalty:Number(x.wrongPenalty)}))});if(issues.length)throw new BadRequestException({message:'Pattern is not publishable',issues});const existing=await database.admissionPatternVersion.findMany({where:{id:{not:id},status:'PUBLISHED',pattern:{universityId:row.pattern.universityId},programApplicability:{some:{programId:{in:row.programApplicability.map(x=>x.programId)}}}},include:{programApplicability:true}});const overlap=findOverlappingPatternIds({id,effectiveFrom:row.effectiveFrom,...(row.effectiveUntil?{effectiveUntil:row.effectiveUntil}:{}),programIds:row.programApplicability.map(x=>x.programId)},existing.filter(x=>x.effectiveFrom).map(x=>({id:x.id,effectiveFrom:x.effectiveFrom!,...(x.effectiveUntil?{effectiveUntil:x.effectiveUntil}:{}),programIds:x.programApplicability.map(p=>p.programId)})));if(overlap.length)throw new ConflictException({message:'Published pattern range overlaps',patternVersionIds:overlap});}
    return database.$transaction(async tx=>{const updated=await tx.admissionPatternVersion.update({where:{id},data:{status:command.to,...(command.to==='PUBLISHED'?{publishedAt:new Date()}:{})}});await tx.auditEvent.create({data:{tenantId:context.principal.tenantId,actorId:context.principal.userId,eventType:`PATTERN_${command.to}`,resourceType:'AdmissionPatternVersion',resourceId:id,correlationId:context.correlationId,reason:command.reason,summary:{from:row.status,to:command.to}}});return updated;});}
  private async requireUniversity(context:RequestContext,id:string){const row=await database.university.findFirst({where:{id,tenantId:context.principal.tenantId}});if(!row)throw new NotFoundException();return row;}
}
