import { createHash } from 'node:crypto';
import { BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException } from '@nestjs/common';
import { database,Prisma } from '@uaprep/db';
import { assertQuestionTransition,canPublishRights,lintQuestion,normalizedQuestionHashInput,type QuestionStatus } from '@uaprep/core';
import type { RequestContext } from '../request-context.js';
import { approvalSchema,createAssignmentSchema,createContentSourceSchema,createQuestionSchema,reviewSchema,rightsReviewSchema,transitionQuestionSchema,validationSchema } from './dto.js';

@Injectable()
export class QuestionsService {
  async createContentSource(ctx:RequestContext,input:unknown){const data=createContentSourceSchema.parse(input);return database.contentSource.create({data:{tenantId:ctx.principal.tenantId,name:data.name,sourceType:data.sourceType,rightsStatus:data.rightsStatus,copyrightOwner:data.copyrightOwner??null,licenseReference:data.licenseReference??null,licenseExpiresAt:data.licenseExpiresAt??null,...(data.metadata!==undefined?{metadata:data.metadata as Prisma.InputJsonValue}:{})}});}
  async createAssignment(ctx:RequestContext,input:unknown){const data=createAssignmentSchema.parse(input);const subject=await database.subject.findFirst({where:{id:data.subjectId,tenantId:ctx.principal.tenantId}});if(!subject)throw new BadRequestException('Subject does not belong to tenant');return database.questionAssignment.create({data:{tenantId:ctx.principal.tenantId,setterId:data.setterId,subjectId:data.subjectId,universityPatternId:data.universityPatternId??null,topicId:data.topicId??null,learningObjectiveId:data.learningObjectiveId??null,numberRequired:data.numberRequired,difficultyMix:data.difficultyMix as Prisma.InputJsonValue,questionType:data.questionType,targetTimeSeconds:data.targetTimeSeconds??null,deadlineAt:data.deadlineAt??null,instructions:data.instructions??null,createdById:ctx.principal.userId}});}
  async createQuestion(ctx:RequestContext,input:unknown){const data=createQuestionSchema.parse(input);const objective=await database.learningObjective.findFirst({where:{id:data.version.objectiveId,topic:{subject:{tenantId:ctx.principal.tenantId}}}});if(!objective)throw new BadRequestException('Learning objective does not belong to tenant');if(data.assignmentId){const assignment=await database.questionAssignment.findFirst({where:{id:data.assignmentId,tenantId:ctx.principal.tenantId,setterId:ctx.principal.userId}});if(!assignment)throw new ForbiddenException('Assignment is not owned by setter');}
    const version=data.version;const lint=lintQuestion({...version});const hash=createHash('sha256').update(normalizedQuestionHashInput(version.stem,version.options)).digest('hex');const duplicate=await database.questionVersion.findFirst({where:{normalizedHash:hash,question:{tenantId:ctx.principal.tenantId}}});if(duplicate)throw new ConflictException({message:'Exact duplicate question detected',questionVersionId:duplicate.id});
    return database.$transaction(async tx=>{const question=await tx.question.create({data:{tenantId:ctx.principal.tenantId,canonicalCode:data.canonicalCode,setterId:ctx.principal.userId,status:'DRAFT'}});const created=await tx.questionVersion.create({data:{questionId:question.id,version:1,objectiveId:version.objectiveId,questionType:version.questionType,language:version.language,stem:version.stem,solution:version.solution,studentExplanation:version.studentExplanation,commonMistake:version.commonMistake??null,shortcut:version.shortcut??null,intendedDifficulty:version.intendedDifficulty,targetTimeSeconds:version.targetTimeSeconds,marks:version.marks,wrongPenalty:version.wrongPenalty,sourceType:version.sourceType,contentSourceId:version.contentSourceId??null,provenance:version.provenance as Prisma.InputJsonValue,rightsStatus:version.rightsStatus,officialQuestion:false,normalizedHash:hash,options:{create:version.options}}});await tx.question.update({where:{id:question.id},data:{currentVersionId:created.id}});if(data.assignmentId)await tx.questionAssignment.update({where:{id:data.assignmentId},data:{questionId:question.id,status:'IN_PROGRESS'}});if(lint.length)await tx.questionLintResult.createMany({data:lint.map(item=>({questionId:question.id,questionVersionId:created.id,code:item.code,severity:item.severity,field:item.field??null,message:item.message}))});await this.audit(tx,ctx,'QUESTION_CREATED','Question',question.id,{version:1,lintCount:lint.length});return {...question,currentVersionId:created.id,lintResults:lint};});}
  async createRevision(ctx:RequestContext,id:string,input:unknown){const data=createQuestionSchema.pick({version:true}).parse(input);const question=await this.question(ctx,id,true);if(question.setterId!==ctx.principal.userId)throw new ForbiddenException();if(!['DRAFT','REVISION_REQUIRED','QUARANTINED'].includes(question.status))throw new ConflictException('Current workflow state does not permit a revision');const latest=Math.max(...question.versions.map(v=>v.version));const version=data.version;const hash=createHash('sha256').update(normalizedQuestionHashInput(version.stem,version.options)).digest('hex');const lint=lintQuestion({...version});return database.$transaction(async tx=>{const created=await tx.questionVersion.create({data:{questionId:id,version:latest+1,objectiveId:version.objectiveId,questionType:version.questionType,language:version.language,stem:version.stem,solution:version.solution,studentExplanation:version.studentExplanation,commonMistake:version.commonMistake??null,shortcut:version.shortcut??null,intendedDifficulty:version.intendedDifficulty,targetTimeSeconds:version.targetTimeSeconds,marks:version.marks,wrongPenalty:version.wrongPenalty,sourceType:version.sourceType,contentSourceId:version.contentSourceId??null,provenance:version.provenance as Prisma.InputJsonValue,rightsStatus:version.rightsStatus,officialQuestion:false,normalizedHash:hash,options:{create:version.options}}});await tx.question.update({where:{id},data:{currentVersionId:created.id,status:'DRAFT'}});if(lint.length)await tx.questionLintResult.createMany({data:lint.map(item=>({questionId:id,questionVersionId:created.id,code:item.code,severity:item.severity,field:item.field??null,message:item.message}))});await this.audit(tx,ctx,'QUESTION_REVISION_CREATED','Question',id,{version:latest+1});return created;});}
  async getQuestion(ctx:RequestContext,id:string,includeKey=false){const question=await this.question(ctx,id,true);return {...question,versions:question.versions.map(version=>({...version,options:version.options.map(option=>includeKey?option:{id:option.id,position:option.position,content:option.content})}))};}
  async listProduction(ctx:RequestContext){return database.question.findMany({where:{tenantId:ctx.principal.tenantId,status:'APPROVED_PRODUCTION'},select:{id:true,canonicalCode:true,status:true,currentVersionId:true,createdAt:true}});}
  async recordReview(ctx:RequestContext,id:string,type:'SME'|'FAIRNESS',input:unknown){const data=reviewSchema.parse(input);const question=await this.question(ctx,id);if(question.setterId===ctx.principal.userId)throw new ForbiddenException('Setter cannot review own question');if(!question.currentVersionId)throw new ConflictException();return database.questionReview.create({data:{questionId:id,questionVersionId:question.currentVersionId,reviewerId:ctx.principal.userId,reviewType:type,decision:data.decision,comments:data.comments??null}});}
  async validateAnswer(ctx:RequestContext,id:string,input:unknown){const data=validationSchema.parse(input);const question=await this.question(ctx,id,true);if(question.setterId===ctx.principal.userId)throw new ForbiddenException('Setter cannot validate own answer');const version=question.versions.find(v=>v.id===question.currentVersionId);if(!version)throw new ConflictException();const proposed=JSON.stringify(data.independentAnswer);const correct=JSON.stringify(version.options.filter(x=>x.isCorrect).map(x=>x.position));const decision=proposed===correct?'MATCH':'DISAGREEMENT';return database.answerValidation.create({data:{questionId:id,questionVersionId:version.id,validatorId:ctx.principal.userId,independentAnswer:data.independentAnswer as Prisma.InputJsonValue,reasoning:data.reasoning,decision,setterKeyRevealedAt:new Date()}});}
  async reviewRights(ctx:RequestContext,id:string,input:unknown){const data=rightsReviewSchema.parse(input);const question=await this.question(ctx,id);if(!question.currentVersionId)throw new ConflictException();return database.rightsReview.create({data:{questionId:id,questionVersionId:question.currentVersionId,reviewerId:ctx.principal.userId,status:data.status,evidence:data.evidence as Prisma.InputJsonValue}});}
  async approve(ctx:RequestContext,id:string,input:unknown){const data=approvalSchema.parse(input);const question=await this.question(ctx,id);if(question.setterId===ctx.principal.userId)throw new ForbiddenException('Setter cannot approve own question');if(!question.currentVersionId)throw new ConflictException();return database.questionApproval.create({data:{questionId:id,questionVersionId:question.currentVersionId,approverId:ctx.principal.userId,decision:data.decision,checklist:data.checklist as Prisma.InputJsonObject,reason:data.reason??null}});}
  async transition(ctx:RequestContext,id:string,input:unknown){const command=transitionQuestionSchema.parse(input);const question=await this.question(ctx,id,true);const current=question.versions.find(v=>v.id===question.currentVersionId);if(!current)throw new ConflictException('Current version is missing');const blocking=question.lintResults.filter(x=>x.questionVersionId===current.id&&x.severity==='ERROR').length;const rights=question.rightsReviews.filter(x=>x.questionVersionId===current.id).at(-1)?.status??current.rightsStatus;assertQuestionTransition(question.status as QuestionStatus,command.to,{actorId:ctx.principal.userId,setterId:question.setterId,rightsPublishable:canPublishRights(rights),blockingLintCount:blocking});this.assertPrerequisites(question,command.to,current.id);
    this.assertTransitionActor(ctx,question.setterId,command.to);
    return database.$transaction(async tx=>{const updated=await tx.question.update({where:{id},data:{status:command.to}});await tx.questionWorkflowEvent.create({data:{questionId:id,actorId:ctx.principal.userId,fromStatus:question.status,toStatus:command.to,reason:command.reason}});await this.audit(tx,ctx,'QUESTION_STATUS_CHANGED','Question',id,{from:question.status,to:command.to,versionId:current.id});return updated;});}
  private assertPrerequisites(question:Awaited<ReturnType<QuestionsService['question']>>,to:string,versionId:string){const reviews=question.reviews.filter(x=>x.questionVersionId===versionId);if(to==='ANSWER_VALIDATION'&&!reviews.some(x=>x.reviewType==='SME'&&x.decision==='APPROVED'))throw new BadRequestException('Approved SME review is required');if(to==='FAIRNESS_REVIEW'&&!question.answerValidations.some(x=>x.questionVersionId===versionId&&x.decision==='MATCH'))throw new BadRequestException('Matching independent validation is required');if(to==='RIGHTS_REVIEW'&&!reviews.some(x=>x.reviewType==='FAIRNESS'&&x.decision==='APPROVED'))throw new BadRequestException('Approved fairness review is required');if(to==='APPROVAL_PENDING'&&!question.rightsReviews.some(x=>x.questionVersionId===versionId&&canPublishRights(x.status)))throw new BadRequestException('Publishable rights review is required');if(to==='APPROVED_FOR_PILOT'&&!question.approvals.some(x=>x.questionVersionId===versionId&&x.decision==='APPROVED_FOR_PILOT'))throw new BadRequestException('Pilot approval checklist is required');if(to==='APPROVED_PRODUCTION'&&!question.approvals.some(x=>x.questionVersionId===versionId&&x.decision==='APPROVED_PRODUCTION'))throw new BadRequestException('Production approval checklist is required');}
  private assertTransitionActor(ctx:RequestContext,setterId:string,to:string){const roles=new Set(ctx.principal.roles);const allowed=to==='SUBMITTED'||to==='DRAFT'?ctx.principal.userId===setterId:to==='IN_REVIEW'||to==='ANSWER_VALIDATION'?roles.has('SUBJECT_REVIEWER')||roles.has('ACADEMIC_DIRECTOR'):to==='FAIRNESS_REVIEW'?roles.has('ANSWER_VALIDATOR')||roles.has('ACADEMIC_DIRECTOR'):to==='RIGHTS_REVIEW'?roles.has('FAIRNESS_REVIEWER')||roles.has('ACADEMIC_DIRECTOR'):to==='APPROVAL_PENDING'?roles.has('ACADEMIC_DIRECTOR'):['APPROVED_FOR_PILOT','APPROVED_PRODUCTION','PILOTING','QUARANTINED','RETIRED','ARCHIVED'].includes(to)?roles.has('ACADEMIC_APPROVER')||roles.has('ACADEMIC_DIRECTOR'):false;if(!allowed)throw new ForbiddenException('Role cannot perform this workflow transition');}
  private async question(ctx:RequestContext,id:string,details=false){const row=await database.question.findFirst({where:{id,tenantId:ctx.principal.tenantId},include:{versions:{include:{options:true}},lintResults:details,reviews:details,answerValidations:details,rightsReviews:details,approvals:details}});if(!row)throw new NotFoundException();return row;}
  private async audit(tx:Prisma.TransactionClient,ctx:RequestContext,eventType:string,resourceType:string,resourceId:string,summary?:object){await tx.auditEvent.create({data:{tenantId:ctx.principal.tenantId,actorId:ctx.principal.userId,eventType,resourceType,resourceId,correlationId:ctx.correlationId,...(summary?{summary:summary as Prisma.InputJsonObject}:{})}});}
}
